# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-14 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_server', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alarm',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='device',
            name='alarm_type',
            field=models.CharField(blank=True, choices=[('BL', 'Block'), ('NT', 'Notification')], max_length=2),
        ),
        migrations.AddField(
            model_name='device',
            name='last_modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='control_server.Device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.TextField(unique=True),
        ),
    ]
